#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sam-demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
#spring session
  session:
    store-type: none
#    spring redis
  redis:
    host: 127.0.0.1
    port: 6399
    pool:
      max-active: 8
      max-wait: 5000
      max-idle: 8
    password: 123456
#port
server:
  port: 9090
#spring session
security:
  basic:
    enabled: true

#sam:
#  security:
#    browser:
#      loginPage: /demo-signIn.html

#sam:
#  security:
#      browser:
#        loginType: REDIRECT

#sam:
#  security:
#    code:
#      image:
#        length: 6
#        width: 100
##        需要验证的接口
#        url: /user/*

sam:
  security:
    browser:
      signUpUrl: /demo-signUp.html
    social:
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
      filterProcessesUrl: /qqLogin
      qq:
        app-id: 100550231
        app-secret: 69b6ab57b22f3c2fe6a6149274e3295e
        providerId: callback.do
logging:
  level:
    com.sam:debug

