#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sam-demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
#spring session
  session:
    store-type: none
#port
server:
  port: 8060
#spring session
security:
  basic:
    enabled: true

#sam:
#  security:
#    browser:
#      loginPage: /demo-signIn.html

#sam:
#  security:
#      browser:
#        loginType: REDIRECT

sam:
  security:
    code:
      image:
        length: 6
        width: 100
#        需要验证的接口
        url: /user/*